sources:
  - name: donnees_juin
    schema: VA_raw_data
    tables:
      - name: donnes_velib_juin
        columns:
          - name: Bike
          - name: Departure_Station
          - name: Departure_Station_Name
          - name: Departure_Time
          - name: Departure_Latitude
          - name: Departure_Longitude
          - name: Electric
          - name: Arrival_Station
          - name: Arrival_Station_Name
          - name: Arrival_Time
          - name: Arrival_Latitude
          - name: Arrival_Longitude
          - name: Length
    tables:     
      - name: comptable_piste_cycl
        columns:
          - name: Identifiant du compteur
          - name: Nom du compteur
          - name: Identifiant du site de comptage
          - name: Nom du site de comptage
          - name: Comptage horaire
          - name: Date et heure de comptage
          - name: Date d'installation du site de comptage
          - name: Lien vers photo du site de comptage
          - name: Coordonnées géographiques
          - name: Identifiant technique compteur
          - name: ID Photos
          - name: test_lien_vers_photos_du_site_de_comptage_
          - name: id_photo_1
          - name: url_sites
          - name: type_dimage
          - name: mois_annee_comptage

