sources:
  - name: donnees_juin
    schema: VA_raw_data
    tables:
      - name: donnes_velib_juin
      - name: station_arrondissement
      - name: stations

  - name: pistes cyclables
    schema: VA_clean
    tables:  
      - name: comptage_pistes_cyclables